controller_manager_ns: controller_manager
controller_list:
  - name: cyton_gamma_1500_arm/arm_joint_controller
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - shoulder_roll_joint
    - shoulder_pitch_joint
    - shoulder_yaw_joint
    - elbow_pitch_joint
    - elbow_yaw_joint
    - wrist_pitch_joint
    - wrist_roll_joint

  - name: cyton_gamma_1500_arm/gripper_controller
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - gripper_joint
    - gripper_joint2



